[package]
name = "storage"
version = "5.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0.0", features = ["default", "gzip"] }
clap = "3.0.0-beta.2"
git-version = "0.3.4"
tonic = "0.4.3"
prost = "0.7.0"
tokio = { version = "1.5.0", features = ["full"] }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "v5.0.0" }
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rusqlite = "0.25.1"
hex = "0.4.3"

[[bin]]
name = "bench"
path = "benches/main.rs"

[dev-dependencies]
tempfile = "3.2.0"
quickcheck = "1.0.3"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1

